server:
  port: 8083

spring:
  data:
    redis:
      host: localhost
      port: 6379
  application:
    name: booking-service
  datasource:
    url: jdbc:postgresql://localhost:5432/BookingDB
    username: user
    password: ${POSTGRESS_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

